# Network configuration
network:
  version: 2
  ethernets:
    ens160:
      dhcp4: false
      addresses: 
        - 192.168.29.221/24
      nameservers:
        addresses:
          - 8.8.8.8
          - 8.8.4.4
      routes:
        - to: default
          via: 192.168.29.1
